/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HisnRouteImport } from './routes/hisn'
import { Route as NawawiRouteImport } from './routes/nawawi'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as QuranRouteImport } from './routes/quran'
import { Route as QuranVideoRouteImport } from './routes/quran-video'
import { Route as ReelCoverRouteImport } from './routes/reel-cover'
import { Route as ReelsRouteImport } from './routes/reels'
import { Route as ReelsWatermarkRouteImport } from './routes/reels-watermark'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TweetRouteImport } from './routes/tweet'
import { Route as VideosRouteImport } from './routes/videos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HisnRoute = HisnRouteImport.update({
  id: '/hisn',
  path: '/hisn',
  getParentRoute: () => rootRouteImport,
} as any)
const NawawiRoute = NawawiRouteImport.update({
  id: '/nawawi',
  path: '/nawawi',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranRoute = QuranRouteImport.update({
  id: '/quran',
  path: '/quran',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranVideoRoute = QuranVideoRouteImport.update({
  id: '/quran-video',
  path: '/quran-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelCoverRoute = ReelCoverRouteImport.update({
  id: '/reel-cover',
  path: '/reel-cover',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsRoute = ReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsWatermarkRoute = ReelsWatermarkRouteImport.update({
  id: '/reels-watermark',
  path: '/reels-watermark',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TweetRoute = TweetRouteImport.update({
  id: '/tweet',
  path: '/tweet',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hisn': typeof HisnRoute
  '/nawawi': typeof NawawiRoute
  '/posts': typeof PostsRoute
  '/quran': typeof QuranRoute
  '/quran-video': typeof QuranVideoRoute
  '/reel-cover': typeof ReelCoverRoute
  '/reels': typeof ReelsRoute
  '/reels-watermark': typeof ReelsWatermarkRoute
  '/settings': typeof SettingsRoute
  '/tweet': typeof TweetRoute
  '/videos': typeof VideosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hisn': typeof HisnRoute
  '/nawawi': typeof NawawiRoute
  '/posts': typeof PostsRoute
  '/quran': typeof QuranRoute
  '/quran-video': typeof QuranVideoRoute
  '/reel-cover': typeof ReelCoverRoute
  '/reels': typeof ReelsRoute
  '/reels-watermark': typeof ReelsWatermarkRoute
  '/settings': typeof SettingsRoute
  '/tweet': typeof TweetRoute
  '/videos': typeof VideosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hisn': typeof HisnRoute
  '/nawawi': typeof NawawiRoute
  '/posts': typeof PostsRoute
  '/quran': typeof QuranRoute
  '/quran-video': typeof QuranVideoRoute
  '/reel-cover': typeof ReelCoverRoute
  '/reels': typeof ReelsRoute
  '/reels-watermark': typeof ReelsWatermarkRoute
  '/settings': typeof SettingsRoute
  '/tweet': typeof TweetRoute
  '/videos': typeof VideosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hisn'
    | '/nawawi'
    | '/posts'
    | '/quran'
    | '/quran-video'
    | '/reel-cover'
    | '/reels'
    | '/reels-watermark'
    | '/settings'
    | '/tweet'
    | '/videos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hisn'
    | '/nawawi'
    | '/posts'
    | '/quran'
    | '/quran-video'
    | '/reel-cover'
    | '/reels'
    | '/reels-watermark'
    | '/settings'
    | '/tweet'
    | '/videos'
  id:
    | '__root__'
    | '/'
    | '/hisn'
    | '/nawawi'
    | '/posts'
    | '/quran'
    | '/quran-video'
    | '/reel-cover'
    | '/reels'
    | '/reels-watermark'
    | '/settings'
    | '/tweet'
    | '/videos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HisnRoute: typeof HisnRoute
  NawawiRoute: typeof NawawiRoute
  PostsRoute: typeof PostsRoute
  QuranRoute: typeof QuranRoute
  QuranVideoRoute: typeof QuranVideoRoute
  ReelCoverRoute: typeof ReelCoverRoute
  ReelsRoute: typeof ReelsRoute
  ReelsWatermarkRoute: typeof ReelsWatermarkRoute
  SettingsRoute: typeof SettingsRoute
  TweetRoute: typeof TweetRoute
  VideosRoute: typeof VideosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hisn': {
      id: '/hisn'
      path: '/hisn'
      fullPath: '/hisn'
      preLoaderRoute: typeof HisnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nawawi': {
      id: '/nawawi'
      path: '/nawawi'
      fullPath: '/nawawi'
      preLoaderRoute: typeof NawawiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran': {
      id: '/quran'
      path: '/quran'
      fullPath: '/quran'
      preLoaderRoute: typeof QuranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran-video': {
      id: '/quran-video'
      path: '/quran-video'
      fullPath: '/quran-video'
      preLoaderRoute: typeof QuranVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reel-cover': {
      id: '/reel-cover'
      path: '/reel-cover'
      fullPath: '/reel-cover'
      preLoaderRoute: typeof ReelCoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels': {
      id: '/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof ReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels-watermark': {
      id: '/reels-watermark'
      path: '/reels-watermark'
      fullPath: '/reels-watermark'
      preLoaderRoute: typeof ReelsWatermarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tweet': {
      id: '/tweet'
      path: '/tweet'
      fullPath: '/tweet'
      preLoaderRoute: typeof TweetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HisnRoute: HisnRoute,
  NawawiRoute: NawawiRoute,
  PostsRoute: PostsRoute,
  QuranRoute: QuranRoute,
  QuranVideoRoute: QuranVideoRoute,
  ReelCoverRoute: ReelCoverRoute,
  ReelsRoute: ReelsRoute,
  ReelsWatermarkRoute: ReelsWatermarkRoute,
  SettingsRoute: SettingsRoute,
  TweetRoute: TweetRoute,
  VideosRoute: VideosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
